steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=intellifix-dotenv > /workspace/.env

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/ai:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/intellifix-integration:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "intellifix-integration"
      - "--image"
      - "gcr.io/$PROJECT_ID/ai:$SHORT_SHA"
      - "--platform"
      - "managed"
      - "--region"
      - "europe-west2"
